# Generated by Django 2.0.2 on 2019-12-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(choices=[('M', 'Multiple Choice'), ('F', 'Fill in the Blank'), ('O', 'Options')], max_length=2, null=True)),
                ('topic', models.CharField(choices=[('L', 'Limitations'), ('S', 'Systems'), ('O', 'Operations & OPV')], max_length=15, null=True)),
                ('level', models.CharField(choices=[('1', 'Required Knowlege'), ('2', '80 Percent Item'), ('3', 'probable Understanding'), ('4', 'Indicates good understanding'), ('5', 'Indicates material mastery'), ('6', 'Stump the Chump')], max_length=3, null=True)),
                ('QuestionReferenceCode', models.CharField(max_length=5, null=True)),
                ('questionText', models.CharField(max_length=200, null=True)),
                ('answer', models.CharField(max_length=150, null=True)),
                ('answerDetails', models.CharField(max_length=200, null=True)),
                ('herring1', models.CharField(max_length=150, null=True)),
                ('herringDetails1', models.CharField(max_length=200, null=True)),
                ('herring2', models.CharField(max_length=150, null=True)),
                ('herringDetails2', models.CharField(max_length=200, null=True)),
                ('herring3', models.CharField(max_length=150, null=True)),
                ('herringDetails3', models.CharField(max_length=200, null=True)),
                ('herring4', models.CharField(max_length=150, null=True)),
                ('herringDetails4', models.CharField(max_length=200, null=True)),
                ('reference', models.CharField(max_length=30, null=True)),
                ('explanation', models.CharField(max_length=350, null=True)),
            ],
        ),
    ]
